import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { MdOutlineLocationOn } from "react-icons/md";
import { MdAccessTime } from "react-icons/md";
import { MdOutlineCalendarMonth } from "react-icons/md";
import { MdOutlineCurrencyRupee } from "react-icons/md";
import { MdSearch } from "react-icons/md";
import { FaArrowRightArrowLeft } from "react-icons/fa6";
import { MdFlightTakeoff } from "react-icons/md";
import { MdEmojiTransportation } from "react-icons/md";
import { LiaHotelSolid } from "react-icons/lia";
import { FaPrayingHands } from "react-icons/fa";
import { IoIosMailUnread } from "react-icons/io";
import { IoCallSharp } from "react-icons/io5";
import { FaWhatsapp } from "react-icons/fa";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import { useMutation } from "react-query";
import fetcher from "src/dataProvider";
import axios from "axios";
import Link from "next/link";
import QRCode from 'qrcode.react';
import { Alert, Spin } from 'antd';
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const [packagesList, setPackagesList] = useState([]);
  const [spinner, setSpinner] = useState(false)
  const router = useRouter();


  const getCloudImages = async (url) => {
    const serviceName = 'adil-travels';
    const config = {
      headers: {
        'Content-Type': 'application/json',
        'Service-Name': serviceName,
        'Object-Name': url
      }
    };
    try {
      const response = await axios.get(`${process.env.NEXT_PUBLIC_CLOUD_URL}/upload/get-multiple`, config);
      return response.data.data;
    } catch (error) {
      console.error('Error:', error);
      throw error;
    }
  }

  const { mutate: getPackagesList } = useMutation(
    () => fetcher.get(`/v1/package-details/?page=1&limit=100`, "raw"),
    {
      onSuccess: async (res) => {
        console.log(res.data, "START")
        let allFetchedData = res.data;
        try {
          if (Array.isArray(allFetchedData?.records)) {
            for (let i = 0; i < allFetchedData?.records?.length; i++) {
              const listItem = allFetchedData?.records[i];
              if (listItem.gallery) {
                const listHeaderImages = await getCloudImages(listItem?.gallery?.headerImages);
                listItem.gallery.headerImages = listHeaderImages;
              }
            };
          }
          setPackagesList(allFetchedData);
          setSpinner(false)
        } catch (error) {
          console.error('Error:', error);
        }
      },
      onError: ({ response }) => {
        console.log(response.data.message);
        alert(response.data.message);
      },
    }
  );


  useEffect(() => {
    setSpinner(true)
    getPackagesList();
  }, [])

  console.log(packagesList, "packagesList")

  return (
    <>
      <Spin tip="Loading..." spinning={spinner}>
        <Head>
          <title>Hajj Umrah</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=0" />
          <link rel="icon" href="./favicon.ico" />
        </Head>
        <div>
          <section class="bg-fixed bg-home bg-cover min-h-screen">
            <div class="container mx-auto flex py-44 flex-col">
              <div class="w-full">
                <h1 class="text-7xl text-white pb-4">Best Tour & Travel</h1>
                <p class="text-white text-lg">
                  Chillwave portland ugh, knausgaard fam polaroid iPhone.{" "}
                  <br></br>Man braid swag typewriter affogato, hella selvage wolf{" "}
                  <br />
                  narwhal dreamcatcher.
                </p>
                {/* <a
                class="inline-block text-black font-medium mt-6 rounded-md bg-yellow-500 py-3 px-4"
                href="#"
              >
                Plan Your Custom Umrah
              </a> */}

                <div className="bg-white w-full rounded-lg m-auto py-5 px-12 mt-48 ">
                  {/* <h2 class="text-white mb-5 text-3xl">Search Packages</h2> */}
                  <div className="grid gap-6  md:grid-cols-6">
                    <div class="flex icon-select">
                      {/* <div className="icon">
                      <MdOutlineLocationOn />
                    </div> */}
                      <select>
                        <option>Select Package</option>
                        <option>Kerala</option>
                        <option>Himachal</option>
                        <option>Andaman</option>
                        <option>Thailand</option>
                        <option>Sikkim</option>
                        <option>Maldives</option>
                      </select>
                    </div>
                    <div class="flex icon-select">
                      {/* <div className="icon">
                      <MdAccessTime />
                    </div> */}
                      <input
                        type="date"
                        placeholder="Select date"
                        style={{ border: "none" }}
                      />
                    </div>

                    <div class="flex icon-select">
                      {/* <div className="icon">
                      <MdOutlineCalendarMonth />
                    </div> */}
                      <input
                        type="date"
                        placeholder="Select date"
                        style={{ border: "none" }}
                      />
                    </div>

                    <div class="flex icon-select">
                      {/* <div className="icon">
                      <MdOutlineLocationOn />
                    </div> */}
                      <select>
                        <option>Duration</option>
                        <option>Kerala</option>
                        <option>Himachal</option>
                        <option>Andaman</option>
                        <option>Thailand</option>
                        <option>Sikkim</option>
                        <option>Maldives</option>
                      </select>
                    </div>

                    <div class="flex icon-select">
                      {/* <div className="icon">
                      <MdOutlineLocationOn />
                    </div> */}
                      <select>
                        <option>Price Range</option>
                        <option>Kerala</option>
                        <option>Himachal</option>
                        <option>Andaman</option>
                        <option>Thailand</option>
                        <option>Sikkim</option>
                        <option>Maldives</option>
                      </select>
                    </div>

                    <div class="flex">
                      <button
                        type="button"
                        class="bg-[#00A852] text-white py-3 px-8 text-lg rounded"
                      >
                        <b>Search</b>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section>
            <div className="container px-5 py-10 mx-auto">
              <div className="grid gap-6 mb-6 md:grid-cols-6 sm:grid-cols-2">
                <div
                  className="bg-[#f5f5f5] text-center px-5 py-8 rounded-xl"
                  style={{ border: "1px solid darkgray" }}
                >
                  <div className="w-full flex justify-center items-center pb-5 ">
                    <img
                      src="Mask group.png"
                      style={{ width: "50%" }}
                      className="cursor-pointer"
                    />
                  </div>
                  <p>
                    WE OFFER <br /> DAILY TOURS
                  </p>
                </div>

                <div
                  className="bg-[#f5f5f5] text-center rounded-xl px-5 py-8"
                  style={{ border: "1px solid darkgray" }}
                >
                  <div className="w-full flex justify-center items-center pb-5 ">
                    <img
                      src="m-2.png"
                      style={{ width: "50%" }}
                      className="cursor-pointer"
                    />
                  </div>
                  <p>
                    FLY FROM <br /> 11 CITIES OF INDIA
                  </p>
                </div>

                <div
                  className="bg-[#f5f5f5] text-center rounded-xl px-5 py-8"
                  style={{ border: "1px solid darkgray" }}
                >
                  <div className="w-full flex justify-center items-center pb-5 ">
                    <img
                      src="m-1.png"
                      style={{ width: "50%" }}
                      className="cursor-pointer"
                    />
                  </div>
                  <p>
                    BETTER TOUR <br /> ARRANGEMENTS
                  </p>
                </div>

                <div
                  className="bg-[#f5f5f5] text-center px-4 py-8 rounded-xl"
                  style={{ border: "1px solid darkgray" }}
                >
                  <div className="w-full flex justify-center items-center pb-5 ">
                    <img
                      src="Mask group-4.png"
                      style={{ width: "50%" }}
                      className="cursor-pointer"
                    />
                  </div>
                  <p>
                    HIGHEST STANDARD <br /> OF SERVICES
                  </p>
                </div>

                <div
                  className="bg-[#f5f5f5] text-center px-5 py-8 rounded-xl"
                  style={{ border: "1px solid darkgray" }}
                >
                  <div className="w-full flex justify-center items-center pb-5 ">
                    <img
                      src="Mask group-3.png"
                      style={{ width: "50%" }}
                      className="cursor-pointer"
                    />
                  </div>
                  <p>
                    QUALITY <br /> ACCOMMODATIONS
                  </p>
                </div>

                <div
                  className="bg-[#f5f5f5] text-center px-5 py-8 rounded-xl"
                  style={{ border: "1px solid darkgray" }}
                >
                  <div className="w-full flex justify-center items-center pb-10 ">
                    <img
                      src="Mask group-2.png"
                      style={{ width: "50%" }}
                      className="cursor-pointer"
                    />
                  </div>
                  <p>TRUST & SAFETY</p>
                </div>
              </div>

              <hr class="h-px my-10 bg-gray-200 border-0 w-full dark:bg-gray-700" />

              <h2 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">
                Tour Packages
              </h2>

              <div className="grid gap-10 mb-6 md:grid-cols-3 sm:grid-cols-1">
                {packagesList?.records?.map((item, index) => {
                  const packageUrl = `${process.env.NEXT_PUBLIC_DEPLOYED_SERVER}/package-detail/${item._id}`;
                  return (
                    <div className="bg-[#F5F5F5]" key={index}>
                      <div className="relative	">
                        {
                          item?.gallery?.headerImages
                            ?
                            <div style={{ position: 'relative', height: '300px' }}>
                              <Image src={item?.gallery?.headerImages[0].secure_url} fill sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw" alt='Image' style={{ objectFit: 'cover' }} />
                              {/* <img
                            src={item?.gallery?.headerImages[0].secure_url}
                            className="cursor-pointer"
                            style={{ objectFit: 'cover' }}
                          /> */}
                            </div>
                            :
                            <div style={{ position: 'relative', height: '300px' }}>
                              <Image src="/place-img.jpg" fill sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw" alt='Image' style={{ objectFit: 'cover' }} />
                              {/* <img src="place-img.jpg" className="opacity-70" style={{ objectFit: 'cover' }} /> */}
                            </div>
                        }
                        {/* <img src="place-img.jpg" className="opacity-70"></img> */}
                        {/* <FaArrowRightArrowLeft className="absolute top-5	right-5 bg-white w-12	h-12 rounded-full	p-2" /> */}
                        <p className="text-[#FF7A00] text-sm bg-[#ffffff] rounded-lg px-3 py-2 w-fit	absolute bottom-5	left-5">
                          <b>{item?.durationDays}D / {item?.durationNights}N</b>
                        </p>
                      </div>

                      <div className="p-5">
                        <h1 className="text-2xl">
                          {item?.name}
                        </h1>

                        <hr class="h-px my-4 bg-gray-200 border-0 w-full dark:bg-gray-700" />

                        <div className="grid gap-1 md:grid-cols-4">
                          <div className="flex justify-evenly	text-sm">
                            <MdFlightTakeoff className="mt-1" />
                            <p>Flights</p>
                          </div>

                          <div className="flex justify-evenly text-sm">
                            <MdEmojiTransportation className="mt-1" />
                            <p>Transfers</p>
                          </div>

                          <div className="flex justify-evenly	text-sm">
                            <LiaHotelSolid className="mt-1" />
                            <p>Hotels</p>
                          </div>

                          <div className="flex justify-evenly text-sm	">
                            <FaPrayingHands className="mt-1" />
                            <p>Activities</p>
                          </div>
                        </div>

                        <hr class="h-px my-4 bg-gray-200 border-0 w-full dark:bg-gray-700" />

                        <div className="grid gap-4 md:grid-cols-3">
                          <div>
                            <QRCode value={packageUrl} size={96} />
                            {/* <img
                            src="icons/package/scanner-img.png"
                            className="cursor-pointer"
                          /> */}
                          </div>
                          <div className="col-span-2">
                            <p className="text-[#00A852] mt-5 text-2xl">
                              <b>INR {item?.cost}</b>
                            </p>
                            <p> Per Person</p>
                          </div>
                        </div>

                        <button className="bg-[#00A852] text-white rounded w-full mt-5 p-3" 
                        onClick={() => {router.push(`/package-detail/${item._id}`)}}>
                          {/* <Link href={`/package-detail/${item._id}`}> */}
                            View Detail
                          {/* </Link> */}
                        </button>
                      </div>
                    </div>
                  )
                })}
              </div>
            </div>
          </section>

          <section className="relative">
            <img
              src="cta-bg.jpg"
              style={{ width: "100%", height: "400px" }}
              className="cursor-pointer"
            />
            <div className="text-center absolute text-white top-28 left-10">
              <p className="text-5xl">
                <b>Tailor Made Tour</b>
              </p>
              <p className="text-2xl">Plan Your Custom Made Tour</p>
              <button
                className="py-2 px-5 text-xl mt-5 rounded "
                style={{ border: "1px solid white" }}
              >
                <b>Plan Your Custom Trip</b>
              </button>
            </div>
          </section>

          <section className="">
            <div className="container px-5 py-10 mx-auto">
              <div className="flex flex-wrap w-full mb-12">
                <div className="w-full">
                  <h2 className="text-center text-3xl font-medium title-font mb-2 text-gray-900">
                    Top Attractions
                  </h2>
                </div>
              </div>

              <div className="grid gap-10 mb-6 md:grid-cols-3 sm:grid-cols-1 px-5">
                <div className="bg-[#F5F5F5] text-center">
                  <img src="ta-1.png"></img>
                  <p className="text-2xl pt-5">
                    <b>Makkah</b>
                  </p>
                  <p className="text-lg pt-2">
                    Embark on the Journey of a Lifetime
                  </p>
                  <button className="bg-[#00a852] px-5 py-2 rounded text-white text-lg my-5">
                    View Detail
                  </button>
                </div>

                <div className="bg-[#F5F5F5] text-center">
                  <img src="ta-2.png"></img>
                  <p className="text-2xl pt-5">
                    <b>Jeddah</b>
                  </p>
                  <p className="text-lg pt-2">
                    Explore the Arabian Splendor
                  </p>
                  <button className="bg-[#00a852] px-5 py-2 rounded text-white text-lg my-5">
                    View Detail
                  </button>
                </div>

                <div className="bg-[#F5F5F5] text-center">
                  <img src="ta-1.png"></img>
                  <p className="text-2xl pt-5">
                    <b>Al Madinah Al Munawwarah</b>
                  </p>
                  <p className="text-lg pt-2">
                    Discover the city of lights
                  </p>
                  <button className="bg-[#00a852] px-5 py-2 rounded text-white text-lg my-5">
                    View Detail
                  </button>
                </div>
              </div>
            </div>
          </section>


          <section>
            <div className="container px-10 py-10 mx-auto bg-[#f5f5f5] p-10">
              <h1 className="text-2xl"><b>Why Travel with us?</b></h1>
              <p className="leading-10 pt-3">Established in 2000, Adil Travels has since positioned itself as one of the leading companies, providing great offers, competitive airfares, exclusive discounts, and a seamless online booking experience to many of its customers. The experience of booking your flight tickets, hotel stay, and holiday package through our desktop site or mobile app can be done with complete ease and no hassles at all. We also deliver amazing offers, such as Instant Discounts, Fare Calendar, MyRewardsProgram, MyWallet, and many more while updating them from time to time to better suit our customers’ evolving needs and demands.</p>
              <div className="grid gap-10 mb-6 md:grid-cols-4 sm:grid-cols-1 mt-6">
                <div className="flex p-3 justify-around	items-center bg-[#C0E4FF]">
                  <IoIosMailUnread style={{ width: '40px', height: '40px' }} />
                  Email Us <br />support@adiltravel.com
                </div>
                <div className="flex p-3 justify-around	items-center bg-[#F3EBCF]">
                  <IoCallSharp style={{ width: '40px', height: '40px' }} />
                  Call Us <br />+91- 123456789
                </div>
                <div className="flex p-3 justify-around	items-center bg-[#CEF4CF]">
                  <FaWhatsapp style={{ width: '40px', height: '40px' }} />
                  Whatsapp <br />+91-123456789
                </div>
              </div>
            </div>
          </section>

          <section>
            <div className="container py-10 mx-auto ">

              <div className="grid gap-10 mb-6 md:grid-cols-3 sm:grid-cols-1 mt-6">

                <div className=" p-5 rounded-xl" style={{ border: '4px solid #f5f5f5' }}>
                  <p className="text-xl py-2"><b>Custom tour from Adil Travels</b></p>
                  <p className="text-base	">MakeMyTrip has since positioned itself as one of the leading companies, providing great offers, competitive airfares, exclusive discounts, and a seamless online booking experience to many of its customers. The experience of booking your flight tickets, hotel stay, and holiday package through our desktop site or mobile app can be done with complete ease and no hassles at all. We also deliver amazing offers, such as Instant Discounts, Fare Calendar, MyRewardsProgram, MyWallet, and many more while updating them from time to time to better suit our customers’ evolving needs and demands.</p>
                </div>

                <div className=" p-5 rounded-xl" style={{ border: '4px solid #f5f5f5' }}>
                  <p className="text-xl py-2"><b>Custom tour from Adil Travels</b></p>
                  <p className="text-base	">MakeMyTrip has since positioned itself as one of the leading companies, providing great offers, competitive airfares, exclusive discounts, and a seamless online booking experience to many of its customers. The experience of booking your flight tickets, hotel stay, and holiday package through our desktop site or mobile app can be done with complete ease and no hassles at all. We also deliver amazing offers, such as Instant Discounts, Fare Calendar, MyRewardsProgram, MyWallet, and many more while updating them from time to time to better suit our customers’ evolving needs and demands.</p>
                </div>

                <div className=" p-5 rounded-xl" style={{ border: '4px solid #f5f5f5' }}>
                  <p className="text-xl py-2"><b>Custom tour from Adil Travels</b></p>
                  <p className="text-base	">MakeMyTrip has since positioned itself as one of the leading companies, providing great offers, competitive airfares, exclusive discounts, and a seamless online booking experience to many of its customers. The experience of booking your flight tickets, hotel stay, and holiday package through our desktop site or mobile app can be done with complete ease and no hassles at all. We also deliver amazing offers, such as Instant Discounts, Fare Calendar, MyRewardsProgram, MyWallet, and many more while updating them from time to time to better suit our customers’ evolving needs and demands.</p>
                </div>

              </div>
            </div>
          </section>


        </div>
      </Spin>
    </>
  );
}
